docs: Removed the bug from the Time Series Regression Code block
Changed 
```python
X_test, _ = load_covid_3month(split="test")
```
To
```python
X_test, y_test = load_covid_3month(split="test")
y_test = y_test.astype("float")
```
`y_test` was not defined but was used later, also  changed the type of `y_test` to remove the the following ValueError
```md
ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.
```