[BUG] in `CNNRegressor`, fix `self.model not found` error when `verbose=True` (#6232)
In the original code, setting verbose=True leads to an AttributeError:
'CNNRegressor' object has no attribute 'model' error. So change

```python
if self.verbose:
    self.model.summary()
```

to

```python
if self.verbose:
    self.model_.summary()
```

because at [code line
187](https://github.com/sktime/sktime/blob/d86114f33aaa3398306f2b93ce3ce03c56b19877/sktime/regression/deep_learning/cnn.py#L187), we don't have define `self.model` in our code