Fix typo in Setting up a development environment section
Fix typo in Setting up a development environment section on Windows

In Install required packages section:

Running pip install numpy=1.19.3 gives this error:

(base) C:\Development\alan-turing-institute\sktime>pip install numpy=1.19.3
ERROR: Invalid requirement: 'numpy=1.19.3'
Hint: = is not a valid operator. Did you mean == ?

Hence pip install numpy=1.19.3 should be pip install numpy==1.19.3.