[DOC] Fix syntax error in "getting started" example code block for Time Series Regression (#6022)
- fixes #6021

Changed 
```python
X_test, _ = load_covid_3month(split="test")
```
To
```python
X_test, y_test = load_covid_3month(split="test")
y_test = y_test.astype("float")
```
`y_test` was not defined but was used later, also changed the type of
`y_test` to remove the the following ValueError
```txt
ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.
```