[BUG] `AttentionLSTM` - Remove activity regularizers (#7582)
#### Reference Issues/PRs
Fixes #6685
Also relevant to #6153 (second issue)

#### What does this implement/fix? Explain your changes.
I fixed the following issues with `AttentionLSTM` used in
`LSTMFCNNetwork`:

-  Removed the unused `activity_regularizer`, which was causing errors
- Changed the name of the first argument in `call` from `inputs` to
`sequences` to match what is expected by keras. Apparently, the argument
names need to match the arguments from the parent class (RNN, in this
case).
- Added `register_keras_serializable` to the code as required by keras
(see
[here](https://keras.io/guides/serialization_and_saving/#custom-objects))
- Changed `use_chrono_initialization` to `unit_forget_bias` as the
former was never initialized, and, therefore, could not be loaded upon
deserialization


In case it's helpful, here's the error that pointed me to changing the
arguments from `inputs` to `sequences`.
```shell
ValueError: Exception encountered when calling AttentionLSTM.call().

  For a `compute_output_shape()` method with more than one argument, all arguments should have a `_shape` suffix and match an argument from `call()`. E.g. `compute_output_shape(self, foo_shape, bar_shape)`  For layer 'AttentionLSTM', received `compute_output_shape()` argument `sequences_shape`, but `call()` does not have argument `sequences`.
```