[BUG] Fix `TimesFM` `_safe_import` (#8511)
#### What does this implement/fix? Explain your changes.

I fixed a small typo in sktime/libs/timesfm/timesfm.py which was causing
the following error while trying to use TimesFMForecaster:

`
TypeError: snapshot_download() takes no arguments
`